version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: always

  app:
    build: .
    command: >
      sh -c "python manage.py wait_for_database &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=supersecretkey
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    networks:
      - backend
    depends_on:
      - db

networks:
  backend:
